import React from 'react';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AOSInit } from './aos';
import LoadingWrapper from './LoadingWrapper'; // New client-side component for handling loading state

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Tame Impala",
  description: "Generated by syd",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
      <body className={inter.className + " w-full overflow-hidden"}>
        {/* <LoadingWrapper> */}
        <AOSInit />
          {children}
        {/* </LoadingWrapper> */}
      </body>
    </html>
  );
}
